import {ranks,companies,upgrades,skills,equipment,slots,events} from './content.mjs';
import {fresh,rate,xpRate,cost,effective,unlocked,promotion,settle,command} from './engine.mjs';
import {SaveRepository,envelope,decode} from './save.mjs';
import {scene} from './scene.mjs';
const paths={case:'M8 7V4h8v3M3 7h18v14H3zM3 12h18M10 12v3h4v-3',office:'M3 21h18M5 21V3h14v18M9 7h1m4 0h1M9 11h1m4 0h1M10 21v-5h4v5',chart:'M4 20V4M4 20h17M8 15l4-5 4 2 5-7',bolt:'m13 2-9 12h7l-1 8 10-13h-7z',target:'M12 8a4 4 0 1 0 4 4M12 3a9 9 0 1 0 9 9M12 12l9-9m-5 0h5v5',book:'M12 5C8 2 3 4 3 4v16s5-2 9 1c4-3 9-1 9-1V4s-5-2-9 1Zm0 0v16',chat:'M21 4H3v13h5v4l5-4h8z',gear:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z',more:'M5 11h1v2H5zm6 0h1v2h-1zm6 0h1v2h-1z',arrow:'M5 12h14m-5-5 5 5-5 5',check:'m5 12 4 4L19 6',lock:'M7 10V7a5 5 0 0 1 10 0v3M5 10h14v11H5z',clock:'M12 8v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',leaf:'M20 3Q3 2 4 14q2 9 10 4 5-4 6-15ZM5 19 15 9',gift:'M3 9h18v5H3zM5 14v7h14v-7M12 9v12M12 9q-9 0-6-5 3-3 6 5Zm0 0q9 0 6-5-3-3-6 5Z',laptop:'M4 3h16v13H4zM2 20h20l-2-4H4z',phone:'M7 2h10v20H7zM10 18h4',suit:'m8 3-6 5 3 5 2-2v10h10V11l2 2 3-5-6-5-4 4z',shoes:'M4 7h5l2 6 9 3v4H3V9z',watch:'M9 2h6v5H9zM9 17h6v5H9zM17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0',bag:'M4 8h16l1 13H3zM8 8V5a4 4 0 0 1 8 0v3',accessory:'M4 7h16v13H4zM7 4h10M8 12h8',download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4',close:'m6 6 12 12M6 18 18 6'};
const icon=(id,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[id]||paths.case}"/></svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'₩'+BigInt(n).toLocaleString('ko-KR');
const time=n=>n>=3600?`${Math.floor(n/3600)}시간 ${Math.floor(n%3600/60)}분`:`${Math.floor(n/60)}분 ${n%60}초`;
const repo=new SaveRepository();let state,committed,revision=0,screen='office',busy=false,saveError='',lastSave=0,toastTimer,modalKind='',backgroundAt=0;
const app=document.querySelector('#app'),dialog=document.querySelector('#dialog');
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3500);}
function sound(){if(!state.settings.sound)return;try{const ctx=new AudioContext();const o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.setValueAtTime(660,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(880,ctx.currentTime+.08);g.gain.setValueAtTime(.04,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.16);o.start();o.stop(ctx.currentTime+.17);o.onended=()=>ctx.close();}catch{}}
function nav(){return [['office','office','업무'],['career','chart','커리어'],['skills','book','능력 개발'],['equipment','bag','장비'],['more','more','더보기']].map(([id,i,label])=>`<button class="nav-item ${screen===id?'active':''}" data-nav="${id}" ${screen===id?'aria-current="page"':''}>${icon(i)}<span>${label}</span>${screen===id?'<span class="nav-dot"></span>':''}</button>`).join('');}
function shell(){app.innerHTML=`<div class="layout"><aside class="sidebar"><a class="brand" href="#office"><span class="brand-mark">${icon('case')}</span><span>직장인 키우기<small>작은 책상, 큰 내일</small></span></a><div class="side-label">MY WORK LIFE</div><nav aria-label="주 메뉴" id="navigation">${nav()}</nav><div class="sidebar-bottom"><div class="side-note">${icon('leaf')}<p>오늘도 나의 속도로.<br><span>성장은 계속되고 있어요.</span></p></div><div class="build-label"><span class="status-dot"></span> LOCAL PLAY <span>v0.1</span></div></div></aside><div class="workspace"><header class="topbar"><div class="crumb">나의 직장 생활 <span>/</span> <strong id="crumb-current">업무</strong></div><div class="topbar-right"><span id="save-status" class="save-status">${icon('check')} 자동 저장 중</span><button class="icon-button" data-action="settings" aria-label="설정">${icon('gear')}</button><div class="avatar">김</div></div></header><main id="main"></main><footer class="footer"><span>작은 성취가 쌓여, 나만의 커리어가 됩니다.</span><span>계정 없이 · 이 브라우저에 저장</span></footer></div></div>`;render();}
function heading(kicker,title,desc,aside=''){return `<div class="page-heading"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${desc}</p></div>${aside}</div>`;}
function office(){const c=companies.find(c=>c.id===state.company);return `${heading('ANOTHER DAY, A LITTLE GROWTH','오늘도, 한 뼘 더 성장해요.','열심히 일하는 김사원. 당신은 다음 한 걸음만 골라 주세요.',`<div class="day-chip">${icon('clock')} 커리어 ${Math.floor(state.seconds/3600)+1}개월차</div>`)}
<section class="finance" aria-label="현재 자산"><div class="balance"><span class="section-label">내 지갑</span><strong id="cash">${money(state.cash)}</strong><span class="subtle">차곡차곡 쌓이는 나의 가능성</span></div><div class="income"><span class="income-icon">${icon('chart')}</span><div><span class="section-label">자동 급여</span><strong><span id="rate">${money(rate(state))}</span><small> / 초</small></strong><span class="income-live"><i></i> 지금도 벌고 있어요</span></div></div><div class="level-block"><div class="between"><strong id="level">Lv. ${state.level}</strong><span id="xp-label">${state.xp} / ${100*state.level**2} XP</span></div><div class="progress"><i id="xp-bar" style="width:${Math.min(100,state.xp/(100*state.level**2)*100)}%"></i></div><span class="subtle">꾸준함도 능력이니까요.</span></div></section>
<div class="office-grid"><div class="office-left"><section class="scene-card ${c.theme}"><div class="scene-heading"><div class="profile-icon">${icon('case')}</div><div><h2>김사원 <span>${ranks[state.rank].name}</span></h2><p>${c.name} · ${22+Math.floor(state.seconds/43200)}세</p></div><span class="working-tag"><i></i> 업무 중</span></div><button class="worker-tap" data-action="worker" aria-label="김사원 응원하기">${scene()}</button><div class="speech" id="speech">작은 성취도, 성취니까.</div><div class="scene-bottom"><span>${icon('leaf')} 나의 첫 번째 커리어</span><span>오늘도 착실하게 <span class="tiny-star">✦</span></span></div></section><button class="event-banner" data-action="event"><span class="event-icon">${icon('chat')}</span><span><strong id="event-title">${state.pending?'사무실에 새로운 이야기가 도착했어요':'평범한 하루에도 이야기는 있어요'}</strong><small id="event-sub">${state.pending?'어떤 선택을 할지, 잠깐 들어볼까요?':'첫 이야기는 근무 2분 후 찾아와요.'}</small></span>${icon('arrow')}</button></div>
<div class="office-right"><section class="goal-card"><div class="section-label">${icon('target')} 다음 목표</div><h2 id="goal-title"></h2><p id="goal-desc"></p><div id="goal-progress"></div><button class="primary full" data-nav="career">승진 준비하기 ${icon('arrow')}</button></section><section class="upgrade-section"><div class="section-title"><h2>일을 더 잘하는 방법</h2><span>UPGRADE</span></div><div class="upgrade-list">${upgrades.map((u,i)=>`<article class="upgrade-card"><div class="upgrade-top"><span class="tile-icon tone-${i}">${icon(u.icon)}</span><div><h3>${u.name} <small id="level-${u.id}">Lv. ${state.upgrades[u.id]}</small></h3><p>${u.desc}</p></div></div><button class="buy-button" data-action="upgrade" data-key="${u.id}" id="buy-${u.id}"></button></article>`).join('')}</div></section></div></div><div class="quiet-tip">${icon('clock')} 잠시 자리를 비워도 괜찮아요. 최대 8시간 동안 급여와 경험치가 쌓여요.</div>`;}
function career(){const p=promotion(state);const c=companies.find(c=>c.id===state.company);return `${heading('YOUR NEXT CHAPTER','한 계단씩, 더 멀리.','실력을 쌓고 평가를 받아 나만의 커리어를 만들어 가세요.')}<div class="career-grid"><section class="panel"><div class="section-title"><h2>나의 커리어 사다리</h2><span>5 RANKS</span></div><div class="ladder">${ranks.map((r,i)=>`<div class="rank-row ${i===state.rank?'current':''} ${i<state.rank?'complete':''}"><span class="rank-number">${i<state.rank?icon('check'):String(i+1).padStart(2,'0')}</span><div><strong>${r.name}</strong><small>기본 ${money(r.rate)} /초</small></div><span class="rank-status">${i===state.rank?'지금 여기':i<state.rank?'달성':`Lv. ${r.level}`}</span></div>`).join('')}</div></section><section class="panel promotion-panel"><span class="eyebrow">NEXT PROMOTION</span><h2>${p.target?`${p.target.name} 승진 준비`:'최고 직급에 도달했어요!'}</h2><p>${p.target?'모든 조건을 채우면 승진 평가에 도전할 수 있어요.':'지금까지 쌓아온 커리어를 돌아보세요. 장비 수집과 능력 개발은 계속할 수 있어요.'}</p><div id="requirements">${requirements(p)}</div><div class="odds"><strong id="chance">승진 가능성 ${p.chance/100}%</strong><span>최대 4번째 평가에서 확정 · 실패 ${state.failures}/3회</span></div><button class="primary full" id="promote" data-action="promote" ${p.ready?'':'disabled'}>${p.cooldown?`${time(p.cooldown)} 후 평가 가능`:p.ready?'승진 평가 받기':p.target?'성장하며 조건을 채워 주세요':'최고 직급 달성'}</button><small class="muted">평가 비용 없음 · 평가 후 대기 2분 · 실패 시 다음 확률 +10%p</small></section></div><section class="panel company-panel"><div class="section-title"><div><h2>새로운 회사, 새로운 기회</h2><p>현재 ${c.name} · 급여 ×${((c.salary+state.negotiated)/10000).toFixed(2)}</p></div><span id="offer-clock">${state.rank<1?'사원부터 채용 제안 도착':`다음 채용까지 ${time(600-state.seconds%600)}`}</span></div><div class="company-grid">${companies.map(co=>{const offer=state.offers.find(o=>o.company===co.id);const current=co.id===state.company;return `<article class="company-card"><span class="company-logo ${co.theme}">${icon('office')}</span><span class="tag">${co.tag}</span><h3>${co.name}</h3><p>${co.desc}</p><dl><div><dt>급여 배율</dt><dd>×${(co.salary/10000).toFixed(1)}</dd></div><div><dt>기본 승진 확률</dt><dd>${(7000-co.difficulty)/100}%</dd></div><div><dt>필요 전문성</dt><dd>${co.expertise}</dd></div></dl><button class="secondary full" data-action="offer" data-key="${offer?.id||''}" ${!offer||effective(state,'expertise')<co.expertise?'disabled':''}>${current?'현재 근무 중':offer?effective(state,'expertise')>=co.expertise?'이직 제안 수락':`전문성 ${co.expertise} 필요`:'다음 채용을 기다리는 중'}</button>${offer?`<small>제안 유효 ${time(offer.expires-state.seconds)} · 협상 +${Math.min(1000,50*effective(state,'talk'))/100}%p</small>`:''}</article>`;}).join('')}</div><p class="muted">이직 시 성과는 0으로 돌아가요. 직급, 능력과 승진 실패 횟수는 유지돼요.</p></section>`;}
function requirements(p){return p.requirements.map(([label,v,target])=>`<div class="requirement"><div class="between"><span>${label}</span><strong>${v} <small>/ ${target}</small> ${v>=target?'✓':''}</strong></div><div class="progress"><i style="width:${target?Math.min(100,v/target*100):100}%"></i></div></div>`).join('');}
function skillScreen(){return `${heading('INVEST IN YOURSELF','가장 좋은 투자는, 나에게.','한 번 익힌 능력은 이직해도 남아요. 훈련은 즉시 완료돼요.')} ${!unlocked(state)?'<div class="notice">업무 화면에서 첫 업그레이드를 구매하면 능력 개발이 열려요.</div>':''}<div class="skills-grid">${skills.map((k,i)=>`<article class="panel skill-card"><span class="large-icon tone-${i}">${icon(k.icon)}</span><span class="eyebrow">PERSONAL SKILL / 0${i+1}</span><h2>${k.name}</h2><div class="skill-level">${state.skills[k.id]}<small> / 100</small></div><p>${k.desc}</p><div class="skill-effective">장비 포함 <strong>${effective(state,k.id)}</strong> 레벨</div><button class="primary full" id="train-${k.id}" data-action="train" data-key="${k.id}"></button></article>`).join('')}</div><section class="panel note-panel">${icon('book')}<div><h3>오늘 배운 것은 내일의 여유가 돼요.</h3><p>업무력은 급여와 성과를, 전문성은 경험치와 이직 기회를, 말빨은 연봉 협상과 대화를 도와줘요.</p></div></section>`;}
let gearFilter='all';
function gearScreen(){return `${heading('TOOLS FOR A BETTER DAY','내 책상을, 내 스타일로.','필요한 도구를 고르고 장착해 보세요. 장비는 슬롯마다 하나씩 적용돼요.')}<div class="equipment-slots">${Object.entries(slots).map(([slot,label])=>`<button class="slot ${state.equipped[slot]?'filled':''}" data-action="slot" data-key="${slot}" title="${state.equipped[slot]?'장착 해제':'빈 슬롯'}">${icon(slot)}<span>${label}</span><small>${state.equipped[slot]?esc(equipment.find(g=>g.id===state.equipped[slot]).name):'비어 있음'}</small></button>`).join('')}</div>${!unlocked(state)?'<div class="notice">첫 업그레이드를 구매하면 장비 상점이 열려요.</div>':''}<div class="section-title shop-title"><h2>장비 둘러보기 <span>${state.inventory.length}/15 보유</span></h2><select id="gear-filter" aria-label="장비 종류"><option value="all">전체 장비</option>${Object.entries(slots).map(([k,v])=>`<option value="${k}" ${gearFilter===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="gear-grid">${equipment.filter(g=>gearFilter==='all'||g.slot===gearFilter).map(g=>`<article class="gear-card"><div class="gear-visual rarity-${g.rarity==='레어'?'rare':g.rarity==='고급'?'uncommon':'common'}">${icon(g.slot)}<span>${g.rarity}</span></div><div class="gear-info"><small>${slots[g.slot]}</small><h3>${g.name}</h3><p>${Object.entries(g.flat).map(([id,v])=>`${skills.find(k=>k.id===id).name} +${v}`).join(' · ')}${g.income?' · 급여 +2%p':''}</p><button class="secondary full" id="gear-${g.id}" data-action="gear" data-key="${g.id}"></button></div></article>`).join('')}</div>`;}
function more(){return `${heading('A LITTLE LOOK BACK','나만의 이야기가 쌓이는 중.','오늘의 숫자와 작은 순간들을 모아 봤어요.')}<div class="summary-grid"><div class="panel"><span class="section-label">누적 수입</span><strong>${money(state.earned)}</strong><small>소비한 금액도 포함한 근로·이벤트 수입</small></div><div class="panel"><span class="section-label">함께한 시간</span><strong>${time(state.seconds)}</strong><small>자리를 비운 동안 인정된 시간 포함</small></div><div class="panel"><span class="section-label">나의 평판</span><strong>${state.reputation}<small> / 1,000</small></strong><small>동료들과 만든 좋은 기억</small></div></div><div class="career-grid"><section class="panel"><div class="section-title"><h2>커리어 일지</h2><span>${state.journal.length} MOMENTS</span></div>${state.journal.length?`<ol class="journal">${state.journal.map(j=>`<li><span>${time(j.seconds)}</span><p>${esc(j.text)}</p></li>`).join('')}</ol>`:'<div class="empty-state">'+icon('book')+'<h3>아직 첫 페이지예요.</h3><p>승진과 이직, 사무실에서의 선택이<br>여기에 기록될 거예요.</p></div>'}</section><section class="panel"><h2>나의 플레이 공간</h2><p>게임은 계정 없이 이 브라우저에 저장돼요. 다른 기기로 옮기기 전에 저장 파일을 내보내 주세요.</p><button class="settings-row" data-action="settings">${icon('gear')} 게임 설정 ${icon('arrow')}</button><button class="settings-row" data-action="export">${icon('download')} 저장 파일 내보내기 ${icon('arrow')}</button><button class="settings-row" data-action="import">${icon('download')} 저장 파일 가져오기 ${icon('arrow')}</button><div class="version-note"><span class="eyebrow">FIRST CHAPTER · v0.1</span><p>지금은 커리어의 첫 번째 챕터예요.<br>인생, 투자, 창업과 은퇴는 이후 챕터로 계획되어 있어요.</p><a href="./docs/PRODUCT_SPEC.md" target="_blank">프로젝트 기획 문서 보기 ↗</a></div></section></div>`;}
function render(){if(!state)return;document.querySelector('#navigation').innerHTML=nav();document.querySelector('#crumb-current').textContent={office:'업무',career:'커리어',skills:'능력 개발',equipment:'장비',more:'더보기'}[screen];document.querySelector('#main').innerHTML=({office,career,skills:skillScreen,equipment:gearScreen,more}[screen])();document.body.classList.toggle('reduced-motion',state.settings.reducedMotion);refresh();}
function text(id,value){const el=document.getElementById(id);if(el)el.textContent=value;}
function purchaseButton(id,price,label,capped=false,locked=false){const el=document.getElementById(id);if(!el)return;const short=price-BigInt(state.cash);el.disabled=busy||capped||locked||short>0n;el.innerHTML=capped?'최대 레벨':locked?`${icon('lock')} 먼저 조건을 달성해 주세요`:`<span>${label}</span><strong>${money(price)}</strong>`;el.title=short>0n?`${money(short)}이 더 필요해요`:label;}
function refresh(){if(!state)return;text('cash',money(state.cash));text('rate',money(rate(state)));text('level',`Lv. ${state.level}`);text('xp-label',state.level===100?'MAX LEVEL':`${state.xp.toLocaleString()} / ${(100*state.level**2).toLocaleString()} XP`);const bar=document.getElementById('xp-bar');if(bar)bar.style.width=`${Math.min(100,state.xp/(100*state.level**2)*100)}%`;
 for(const u of upgrades){text(`level-${u.id}`,`Lv. ${state.upgrades[u.id]}`);purchaseButton(`buy-${u.id}`,cost(u.base,state.upgrades[u.id]),'업그레이드',state.upgrades[u.id]>=200);}
 for(const k of skills)purchaseButton(`train-${k.id}`,cost(1000,state.skills[k.id],118),'훈련하기',state.skills[k.id]>=100,!unlocked(state));
 for(const g of equipment){const el=document.getElementById(`gear-${g.id}`);if(!el)continue;const owned=state.inventory.includes(g.id),equipped=state.equipped[g.slot]===g.id;el.disabled=busy||equipped||!unlocked(state)||state.rank<g.rank||(!owned&&BigInt(state.cash)<BigInt(g.price));el.textContent=equipped?'✓ 장착 중':state.rank<g.rank?`${ranks[g.rank].name}부터 구매 가능`:owned?'장착하기':`${money(g.price)} · 구매 후 장착`;}
 const p=promotion(state);text('goal-title',p.target?`${p.target.name} 승진까지 한 걸음`:'커리어의 정상에 도착!');text('goal-desc',p.target?'오늘의 꾸준함이 다음 명함이 돼요.':'나만의 속도로 계속 성장해 보세요.');const gp=document.getElementById('goal-progress');if(gp){const first=p.requirements.find(([,a,b])=>a<b);gp.innerHTML=p.target?`<div class="between"><span>${first?`${first[0]} 쌓기`:'모든 성장 조건 달성'}</span><strong>${p.requirements.filter(([,a,b])=>a>=b).length} / 5</strong></div><div class="progress"><i style="width:${p.requirements.filter(([,a,b])=>a>=b).length*20}%"></i></div>`:'<p>다섯 직급을 모두 달성했어요. ✓</p>';}
 const req=document.getElementById('requirements');if(req)req.innerHTML=requirements(p);const promote=document.getElementById('promote');if(promote){promote.disabled=busy||!p.ready;promote.textContent=p.cooldown?`${time(p.cooldown)} 후 평가 가능`:p.ready?'승진 평가 받기':p.target?'성장하며 조건을 채워 주세요':'최고 직급 달성';}
 text('offer-clock',state.rank<1?'사원부터 채용 제안 도착':`다음 채용까지 ${time(600-state.seconds%600)}`);
 text('event-title',state.pending?'사무실에 새로운 이야기가 도착했어요':'평범한 하루에도 이야기는 있어요');text('event-sub',state.pending?'어떤 선택을 할지, 잠깐 들어볼까요?':state.seconds<120?`${time(120-state.seconds)} 후 첫 이야기가 찾아와요.`:'다음 이야기를 기다리는 중이에요.');document.querySelector('.event-banner')?.classList.toggle('has-event',!!state.pending);
 const save=document.querySelector('#save-status');if(save){save.innerHTML=saveError?`${icon('lock')} 저장 실패 · 설정에서 백업`:`${icon('check')} 이 기기에 저장됨`;save.classList.toggle('error',!!saveError);save.title=saveError;}
 document.querySelector('.scene-card')?.classList.toggle('has-laptop',!!state.equipped.laptop);document.querySelector('.scene-card')?.classList.toggle('has-suit',!!state.equipped.suit);document.querySelector('.scene-card')?.classList.toggle('has-bag',!!state.equipped.bag);document.querySelector('.scene-card')?.classList.toggle('has-accessory',!!state.equipped.accessory);
}
function showModal(kind,html){modalKind=kind;dialog.innerHTML=`<button class="dialog-close icon-button" data-action="close" aria-label="닫기">${icon('close')}</button>${html}`;if(!dialog.open)dialog.showModal();}
function closeModal(){dialog.close();modalKind='';}
function eventModal(){if(!state.pending){toast('이야기가 도착하면 알려드릴게요.');return;}const e=events.find(e=>e.id===state.pending.eventId);showModal('event',`<span class="large-icon tone-0">${icon('chat')}</span><div class="eyebrow">OFFICE MOMENT</div><h2>${e.title}</h2><p>${e.body}</p><div class="event-choices">${e.choices.map((c,i)=>`<button class="choice" data-action="event-choice" data-key="${state.pending.id}" data-choice="${i}" ${effective(state,'talk')<(c.talk||0)?'disabled':''}><strong>${c.text}</strong><small>${Object.entries(c.effects).map(([k,v])=>k==='cash'?`${money(v)}`:k==='stress'?'잠깐의 여유 (급여 영향 없음)':`${{performance:'성과',reputation:'평판'}[k]} +${v}`).join(' · ')}${c.talk?` · 말빨 ${c.talk} 필요`:''}</small></button>`).join('')}</div><small class="muted">선택하는 동안에도 급여는 계속 쌓여요.</small>`);}
function offlineModal(){if(!state.offline)return;showModal('offline',`<span class="large-icon tone-1">${icon('clock')}</span><div class="eyebrow">WELCOME BACK</div><h2>자리를 비운 동안</h2><p>${time(state.offline.seconds)} 동안 김사원이 차곡차곡 모았어요.</p><div class="offline-amount">+${money(state.offline.cash)}</div><p>급여와 경험치가 이미 반영됐어요.${state.offline.capped?'<br>한 번의 부재는 최대 8시간까지 인정돼요.':''}</p><button class="primary full" data-action="dismiss-offline">계속하기</button>`);}
function settingsModal(){showModal('settings',`<div class="eyebrow">MAKE YOURSELF AT HOME</div><h2>게임 설정</h2><p>나에게 편안한 플레이를 골라 주세요.</p><label class="toggle-row">효과음<input type="checkbox" data-setting="sound" ${state.settings.sound?'checked':''}></label><label class="toggle-row">움직임 줄이기<input type="checkbox" data-setting="reducedMotion" ${state.settings.reducedMotion?'checked':''}></label><button class="settings-row" data-action="export">${icon('download')} 저장 파일 내보내기</button><button class="settings-row" data-action="import">${icon('download')} 저장 파일 가져오기</button><button class="settings-row" data-action="retry">${icon('check')} 지금 저장하기</button><p class="muted">자동 저장은 5초마다, 구매와 선택은 즉시 저장돼요. 브라우저 데이터를 지우면 진행이 사라질 수 있어요.</p>${saveError?`<div class="notice">${esc(saveError)}</div>`:''}<button class="text-button danger" data-action="reset">새로 시작하기</button>`);}
async function persist(candidate){let saved;try{saved=await repo.commit(candidate,revision);}catch(e){saveError='저장하지 못했어요. '+(e.message||'저장 공간을 확인해 주세요.');state=structuredClone(committed);throw Error(saveError);}revision=saved.revision;state=saved;committed=structuredClone(saved);lastSave=Date.now();saveError='';return saved;}
async function act(kind,extra={}){if(busy)return false;busy=true;try{const settled=settle(state,Date.now());const result=command(settled,{id:crypto.randomUUID(),revision:settled.revision,kind,...extra});await persist(result.state);sound();toast(result.message);render();return true;}catch(e){if(/保存|저장|Quota|transaction|database|창에서/i.test(e.message)){saveError=e.message;state=structuredClone(committed);}toast(e.message||'처리하지 못했어요. 다시 시도해 주세요.');return false;}finally{busy=false;refresh();}}
async function saveNow(away=false){if(busy||!state)return;busy=true;try{const prevOffers=JSON.stringify(state.offers);await persist(settle(state,Date.now(),away));if(screen==='career'&&prevOffers!==JSON.stringify(state.offers))render();if(away&&state.offline&&!dialog.open)offlineModal();}catch(e){saveError=e.message||'저장 공간을 확인해 주세요.';state=structuredClone(committed);toast(saveError);}finally{busy=false;refresh();}}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
async function exportSave(){download(JSON.stringify(await envelope(state),null,2),`office-worker-${new Date().toISOString().slice(0,10)}.json`);toast('저장 파일을 내보냈어요.');}
let imported=null;
function importSave(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{const f=input.files[0];if(!f)return;if(f.size>5*1024*1024)throw Error('5MB 이하의 저장 파일을 선택해 주세요.');imported=await decode(JSON.parse(await f.text()));showModal('import',`<h2>이 커리어로 이어갈까요?</h2><p>${ranks[imported.rank].name} · Lv. ${imported.level}<br>${money(imported.cash)} · ${time(imported.seconds)}</p><p>현재 진행은 교체돼요. 교체 전에 현재 저장 파일을 자동으로 내보내요.</p><button class="primary full" data-action="confirm-import">저장 파일 교체하기</button><button class="secondary full" data-action="close">취소</button>`);}catch(e){toast(e.message);}};input.click();}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.nav){screen=b.dataset.nav;location.hash=screen;render();return;}const a=b.dataset.action;if(!a)return;
 if(a==='close'){if(modalKind==='offline'){if(await act('dismissOffline'))closeModal();}else closeModal();return;}
 if(a==='upgrade'||a==='train'||a==='gear'||a==='offer'){await act(a,{key:b.dataset.key});return;}
 if(a==='promote'){await act('promote');return;}
 if(a==='worker'){const quotes=['한 칸씩 채우다 보면, 언젠가 완성!','오늘의 나는 어제보다 단축키 하나 더 안다.','커피는 따뜻하게, 목표는 천천히.','작은 성취도, 성취니까.'];text('speech',quotes[Math.floor(Math.random()*quotes.length)]);return;}
 if(a==='event')return eventModal();if(a==='settings')return settingsModal();if(a==='event-choice'){if(await act('event',{key:b.dataset.key,choice:Number(b.dataset.choice)}))closeModal();return;}
 if(a==='dismiss-offline'){if(await act('dismissOffline'))closeModal();return;}
 if(a==='slot'){if(state.equipped[b.dataset.key])await act('unequip',{key:b.dataset.key});else toast('아래에서 이 슬롯의 장비를 골라 주세요.');return;}
 if(a==='retry')return saveNow();if(a==='export')return exportSave();if(a==='import')return importSave();
 if(a==='confirm-import'&&imported&&!busy){busy=true;try{await exportSave();const replacement=structuredClone(imported);replacement.last=Date.now();replacement.remainder=0;replacement.offline=null;await persist(replacement);imported=null;closeModal();render();toast('저장 파일을 가져왔어요.');}catch(e){toast(e.message);}finally{busy=false;}return;}
 if(a==='reset'){showModal('reset',`<h2>처음부터 시작할까요?</h2><p>현재 커리어와 장비, 진행 기록을 모두 지우고 새로 시작해요. 이 작업은 되돌릴 수 없어요.</p><button class="secondary full" data-action="export">먼저 저장 파일 내보내기</button><button class="primary full danger-bg" data-action="confirm-reset">진행 삭제 후 시작</button><button class="text-button" data-action="close">계속 플레이하기</button>`);return;}
 if(a==='confirm-reset'&&!busy){busy=true;try{await persist(newState());closeModal();screen='office';render();toast('새로운 첫 출근을 응원해요.');}catch(e){toast(e.message);}finally{busy=false;}}
});
document.addEventListener('change',async e=>{if(e.target.dataset.setting)await act('settings',{key:e.target.dataset.setting,value:e.target.checked});if(e.target.id==='gear-filter'){gearFilter=e.target.value;render();}});
dialog.addEventListener('cancel',e=>{if(modalKind==='offline'){e.preventDefault();act('dismissOffline').then(ok=>{if(ok)closeModal();});}});
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(['office','career','skills','equipment','more'].includes(next)&&next!==screen){screen=next;render();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){backgroundAt=Date.now();saveNow();}else{backgroundAt=0;saveNow(true);}});
function newState(){const s=fresh(Date.now(),crypto.getRandomValues(new Uint32Array(1))[0]||1);s.settings.reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;return s;}
async function boot(){try{await repo.open();const loaded=await repo.load();revision=loaded.revision;state=loaded.state||newState();committed=structuredClone(state);await persist(settle(state,Date.now(),!!loaded.state));const hash=location.hash.slice(1);if(['office','career','skills','equipment','more'].includes(hash))screen=hash;shell();if(loaded.recovered)toast('이전 정상 저장에서 복구했어요.');if(state.offline)offlineModal();setInterval(()=>{if(busy||document.hidden||saveError)return;const oldOffers=JSON.stringify(state.offers);state=settle(state,Date.now());if(oldOffers!==JSON.stringify(state.offers)&&screen==='career')render();else refresh();if(Date.now()-lastSave>=5000)saveNow();},250);}catch(e){app.innerHTML=`<main class="boot"><h1>저장 파일을 확인해 주세요.</h1><p>${esc(e.message)}</p><p>기존 데이터는 보존했어요. 백업을 내보내거나 다시 시도할 수 있어요.</p><button class="primary" id="boot-retry">다시 시도</button><button class="secondary" id="boot-export">원본 데이터 내보내기</button><button class="text-button danger" id="boot-reset">진행 초기화</button></main>`;document.querySelector('#boot-retry').onclick=()=>location.reload();document.querySelector('#boot-export').onclick=async()=>download(JSON.stringify(await repo.raw()),'office-worker-recovery.json');document.querySelector('#boot-reset').onclick=async()=>{if(confirm('복구되지 않은 기존 진행을 삭제할까요? 먼저 원본 데이터를 내보내 주세요.')){await repo.reset();location.reload();}};}}
boot();


